#include-once

Global $Dir_Lang = @ScriptDir&"\data\language\"
Global $catalan = @ScriptDir&"\data\language\catalan.ini"
Global $chinese = @ScriptDir&"\data\language\chinese.ini"
Global $english = @ScriptDir&"\data\language\english.ini"
Global $french = @ScriptDir&"\data\language\french.ini"
Global $german = @ScriptDir&"\data\language\german.ini"
Global $italian = @ScriptDir&"\data\language\italian.ini"
Global $japanese = @ScriptDir&"\data\language\japanese.ini"
Global $korean = @ScriptDir&"\data\language\korean.ini"
Global $polish = @ScriptDir&"\data\language\polish.ini"
Global $portuguese = @ScriptDir&"\data\language\portuguese.ini"
Global $russian = @ScriptDir&"\data\language\russian.ini"
Global $spanish = @ScriptDir&"\data\language\spanish.ini"
Global $turkish = @ScriptDir&"\data\language\turkish.ini"
Global $ukrainian = @ScriptDir&"\data\language\ukrainian.ini"

EmptyIniWrite($catalan, "tray", "01", """Mostra la VM""", "32")
EmptyIniWrite($catalan, "tray", "02", """Oculta la VM""", "32")
EmptyIniWrite($catalan, "tray", "03", """Mostra el VirtualBox""", "32")
EmptyIniWrite($catalan, "tray", "04", """Oculta el VirtualBox""", "32")
EmptyIniWrite($catalan, "tray", "05", """Opcions""", "32")
EmptyIniWrite($catalan, "tray", "06", """Sortant de VirtualBox""", "32")
EmptyIniWrite($catalan, "tray", "07", """Feu clic amb el botó dret per a veure el menú""", "32")
EmptyIniWrite($catalan, "messages", "01", """Error""", "32")
EmptyIniWrite($catalan, "messages", "02", """Desa""", "32")
EmptyIniWrite($catalan, "messages", "03", """Tancar""", "32")
EmptyIniWrite($catalan, "messages", "04", """Desat""", "32")
EmptyIniWrite($catalan, "messages", "05", """Si us plau, recordeu reiniciar el Portable-VirtualBox per tal que les noves opcions tinguin efecte.""", "32")
EmptyIniWrite($catalan, "messages", "06", """Inicia el Portable-VirtualBox""", "32")
EmptyIniWrite($catalan, "messages", "07", """Surt del Portable-VirtualBox""", "32")
EmptyIniWrite($catalan, "start", "01", """Copia els fitxer del VirtualBox a la carpeta corresponent.""", "32")
EmptyIniWrite($catalan, "settings", "01", """Configuració""", "32")
EmptyIniWrite($catalan, "settings", "02", """Executar VirtualBox amb suport de xarxa""", "32")
EmptyIniWrite($catalan, "settings", "03", """Executar VirtualBox amb suport USB""", "32")
EmptyIniWrite($catalan, "settings", "04", """Inicia VirtualBox amb compatibilitat amb tecles d'accés directe a la safata de control""", "32")
EmptyIniWrite($catalan, "settings", "05", """Idioma de la interfície:""", "32")
EmptyIniWrite($catalan, "settings", "06", """Carpeta per desar la configuració de VirtualBox:""", "32")
EmptyIniWrite($catalan, "settings", "07", """Carpeta per desar els fitxers de la màquina:""", "32")
EmptyIniWrite($catalan, "settings", "08", """Executar VirtualBox des de la màquina virtual:""", "32")
EmptyIniWrite($catalan, "settings", "09", """Revisió""", "32")
EmptyIniWrite($catalan, "settings", "10", """Selecciona el directori d'inici""", "32")
EmptyIniWrite($catalan, "settings", "11", """Seleccioneu el directori de la màquina virtual""", "32")
EmptyIniWrite($catalan, "hotkey-settings", "01", """Opcions de HotKeys""", "32")
EmptyIniWrite($catalan, "hotkey-settings", "02", """Si no esteu d'acord amb les opcions predeterminades de les 'HotKeys' (decreres de teclat), aquí podeu especificar altres combinacions de tecles. Nota: Les tecles de control es limiten a Alt, Ctrl i Majús, la tecla restant es pot triar lliurement (per defecte, Ctrl+""1~6"").""", "32")
EmptyIniWrite($catalan, "hotkey-settings", "03", """Valor per defecte (Ctrl+""1~6"")""", "32")
EmptyIniWrite($catalan, "hotkey-settings", "04", """Defineix una clau per al camp d'entrada""", "32")
EmptyIniWrite($catalan, "about", "01", """Sobre el programa...""", "32")
EmptyIniWrite($catalan, "download", "01", """VirtualBox Portable""", "32")
EmptyIniWrite($catalan, "download", "02", """Aquí podeu trobar fitxers d'instal·lació de VirtualBox que es poden descarregar automàticament i fer alguns canvis, només cal que aneu a la configuració i feu clic a ""D'acord"".""", "32")
EmptyIniWrite($catalan, "download", "03", """Baixeu els fitxers d'instal·lació de VirtualBox""", "32")
EmptyIniWrite($catalan, "download", "04", """o""", "32")
EmptyIniWrite($catalan, "download", "05", """El camí del fitxer d'instal·lació del VirtualBox és...""", "32")
EmptyIniWrite($catalan, "download", "06", """Revisió""", "32")
EmptyIniWrite($catalan, "download", "07", """Extreure els fitxers per un sistema de 32 bits""", "32")
EmptyIniWrite($catalan, "download", "08", """Extreure els fitxers per un sistema de 64 bits""", "32")
EmptyIniWrite($catalan, "download", "09", """Comprimiu fitxers per reduir la mida""", "32")
EmptyIniWrite($catalan, "download", "10", """Inicieu VirtualBox Portable després de desempaquetar""", "32")
EmptyIniWrite($catalan, "download", "11", """Informació d'estat:""", "32")
EmptyIniWrite($catalan, "download", "12", """D'acord""", "32")
EmptyIniWrite($catalan, "download", "13", """Llicència de VirtualBox""", "32")
EmptyIniWrite($catalan, "download", "14", """Sortida""", "32")
EmptyIniWrite($catalan, "download", "15", """Info""", "32")
EmptyIniWrite($catalan, "download", "16", """Si us plau, reinicieu VirtualBox per adaptar els camins!""", "32")
EmptyIniWrite($catalan, "status", "01", """Carregant:""", "32")
EmptyIniWrite($catalan, "status", "02", """Descàrrega completa! Els fitxers s'emmagatzemen a la carpeta Portable-VirtualBox.""", "32")
EmptyIniWrite($catalan, "status", "03", """VirtualBox - Instal·lació de fitxers""", "32")
EmptyIniWrite($catalan, "status", "04", """Espereu, els fitxers s'estan desempaquetant.""", "32")
EmptyIniWrite($catalan, "status", "05", """Espereu, els fitxers s'estan copiant.""", "32")
EmptyIniWrite($catalan, "status", "06", """Espereu, compressió de fitxer.""", "32")
EmptyIniWrite($catalan, "status", "07", """Espereu, suprimint fitxers i carpetes""", "32")
EmptyIniWrite($catalan, "status", "08", """S'ha acabat de desempaquetar i copiar els fitxers""", "32")
EmptyIniWrite($catalan, "status", "09", """Espereu, feu una còpia de seguretat de fitxers i carpetes antics.""", "32")
EmptyIniWrite($catalan, "status", "10", """Espereu, baixant les actualitzacions.""", "32")
EmptyIniWrite($catalan, "status", "11", """Espereu, actualitzeu fitxers i carpetes.""", "32")
EmptyIniWrite($catalan, "status", "12", """L'actualització s'ha completat.""", "32")

EmptyIniWrite($chinese, "tray", "01", """显示 VM""", "32")
EmptyIniWrite($chinese, "tray", "02", """隐藏 VM""", "32")
EmptyIniWrite($chinese, "tray", "03", """显示 VirtualBox""", "32")
EmptyIniWrite($chinese, "tray", "04", """隐藏 VirtualBox""", "32")
EmptyIniWrite($chinese, "tray", "05", """设置""", "32")
EmptyIniWrite($chinese, "tray", "06", """退出 VirtualBox""", "32")
EmptyIniWrite($chinese, "tray", "07", """右键单击将打开菜单""", "32")
EmptyIniWrite($chinese, "messages", "01", """错误""", "32")
EmptyIniWrite($chinese, "messages", "02", """保存""", "32")
EmptyIniWrite($chinese, "messages", "03", """关闭""", "32")
EmptyIniWrite($chinese, "messages", "04", """已保存""", "32")
EmptyIniWrite($chinese, "messages", "05", """重新启动 VirtualBox 以应用设置。""", "32")
EmptyIniWrite($chinese, "messages", "06", """开始""", "32")
EmptyIniWrite($chinese, "messages", "07", """关闭 VirtualBox""", "32")
EmptyIniWrite($chinese, "start", "01", """将文件从 VirtualBox 复制到 APP 目录中的相应文件夹""", "32")
EmptyIniWrite($chinese, "settings", "01", """设置""", "32")
EmptyIniWrite($chinese, "settings", "02", """运行具有网络支持的 VirtualBox""", "32")
EmptyIniWrite($chinese, "settings", "03", """运行支持 USB 的 VirtualBox""", "32")
EmptyIniWrite($chinese, "settings", "04", """使用托盘热键支持启动 VirtualBox""", "32")
EmptyIniWrite($chinese, "settings", "05", """界面语言：""", "32")
EmptyIniWrite($chinese, "settings", "06", """保存 VirtualBox 设置的文件夹：""", "32")
EmptyIniWrite($chinese, "settings", "07", """保存机器文件的文件夹：""", "32")
EmptyIniWrite($chinese, "settings", "08", """从虚拟机运行 VirtualBox：""", "32")
EmptyIniWrite($chinese, "settings", "09", """审查""", "32")
EmptyIniWrite($chinese, "settings", "10", """选择主目录""", "32")
EmptyIniWrite($chinese, "settings", "11", """选择虚拟机目录""", "32")
EmptyIniWrite($chinese, "hotkey-settings", "01", """热键设置""", "32")
EmptyIniWrite($chinese, "hotkey-settings", "02", """要设置不被系统占用了的热键。注意：命令键必须为 ALT，CTRL 和 SHIFT 键之一，后面为自定义（默认为 Ctrl + 1 ～ Ctrl + 6）""", "32")
EmptyIniWrite($chinese, "hotkey-settings", "03", """默认 (Ctrl + 1 ～ Ctrl + 6)""", "32")
EmptyIniWrite($chinese, "hotkey-settings", "04", """为输入字段定义一个键""", "32")
EmptyIniWrite($chinese, "about", "01", """关于该计划...""", "32")
EmptyIniWrite($chinese, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($chinese, "download", "02", """在这里你可以设置是下载 VirtralBox 安装文件还是手动指定程序所在位置（如果你使用本程序下载 VirtualBox，只需要选择版本，然后单击""确定""）。""", "32")
EmptyIniWrite($chinese, "download", "03", """下载 VirtualBox 的安装文件""", "32")
EmptyIniWrite($chinese, "download", "04", """或""", "32")
EmptyIniWrite($chinese, "download", "05", """VirtualBox 安装文件的路径...""", "32")
EmptyIniWrite($chinese, "download", "06", """审查""", "32")
EmptyIniWrite($chinese, "download", "07", """提取 32 位系统的文件""", "32")
EmptyIniWrite($chinese, "download", "08", """提取 64 位系统的文件""", "32")
EmptyIniWrite($chinese, "download", "09", """压缩文件，以减少大小""", "32")
EmptyIniWrite($chinese, "download", "10", """解压后启动Portable-VirtualBox""", "32")
EmptyIniWrite($chinese, "download", "11", """状态信息：""", "32")
EmptyIniWrite($chinese, "download", "12", """确定""", "32")
EmptyIniWrite($chinese, "download", "13", """许可证 VirtualBox""", "32")
EmptyIniWrite($chinese, "download", "14", """出口""", "32")
EmptyIniWrite($chinese, "download", "15", """信息""", "32")
EmptyIniWrite($chinese, "download", "16", """请重新启动 VirtualBox 以更改路径!""", "32")
EmptyIniWrite($chinese, "status", "01", """加载中：""", "32")
EmptyIniWrite($chinese, "status", "02", """下载完成！这些文件存储在 Portable-VirtualBox 文件夹中。""", "32")
EmptyIniWrite($chinese, "status", "03", """VirtualBox - 安装文件""", "32")
EmptyIniWrite($chinese, "status", "04", """请稍候，文件正在解压。""", "32")
EmptyIniWrite($chinese, "status", "05", """请稍候，正在复制文件。""", "32")
EmptyIniWrite($chinese, "status", "06", """请稍候，文件压缩。""", "32")
EmptyIniWrite($chinese, "status", "07", """请稍候，正在删除文件和文件夹""", "32")
EmptyIniWrite($chinese, "status", "08", """解压，复制文件完成""", "32")
EmptyIniWrite($chinese, "status", "09", """等等，备份旧文件和文件夹。""", "32")
EmptyIniWrite($chinese, "status", "10", """请稍候，正在下载更新。""", "32")
EmptyIniWrite($chinese, "status", "11", """请稍候，正在更新文件和文件夹。""", "32")
EmptyIniWrite($chinese, "status", "12", """更新完成。""", "32")

EmptyIniWrite($english, "tray", "01", """Show VM""")
EmptyIniWrite($english, "tray", "02", """Hide VM""")
EmptyIniWrite($english, "tray", "03", """Show VirtualBox""")
EmptyIniWrite($english, "tray", "04", """Hide VirtualBox""")
EmptyIniWrite($english, "tray", "05", """Settings""")
EmptyIniWrite($english, "tray", "06", """Exit VirtualBox""")
EmptyIniWrite($english, "tray", "07", """Right-click to see menu""")
EmptyIniWrite($english, "messages", "01", """Error""")
EmptyIniWrite($english, "messages", "02", """Save""")
EmptyIniWrite($english, "messages", "03", """Close""")
EmptyIniWrite($english, "messages", "04", """Saved""")
EmptyIniWrite($english, "messages", "05", """Restart VirtualBox to change settings.""")
EmptyIniWrite($english, "messages", "06", """Starting VirtualBox""")
EmptyIniWrite($english, "messages", "07", """Closing VirtualBox""")
EmptyIniWrite($english, "start", "01", """Copy files from VirtualBox in the corresponding folder in the APP directory""")
EmptyIniWrite($english, "settings", "01", """Settings""")
EmptyIniWrite($english, "settings", "02", """Start VirtualBox with network support""")
EmptyIniWrite($english, "settings", "03", """Start VirtualBox with usb support""")
EmptyIniWrite($english, "settings", "04", """Start VirtualBox with tray hotkey support""")
EmptyIniWrite($english, "settings", "05", """Interface language:""")
EmptyIniWrite($english, "settings", "06", """Folder for saving VirtualBox settings:""")
EmptyIniWrite($english, "settings", "07", """Folder for machines:""")
EmptyIniWrite($english, "settings", "08", """Start VirtualBox with VM:""")
EmptyIniWrite($english, "settings", "09", """Browse""")
EmptyIniWrite($english, "settings", "10", """Select home directory""")
EmptyIniWrite($english, "settings", "11", """Select VM directory""")
EmptyIniWrite($english, "hotkey-settings", "01", """Hot hotkey-settings""")
EmptyIniWrite($english, "hotkey-settings", "02", """Here you can change the hotkey values. Note: you can use the ALT, CTRL and SHIFT keys. (Default = CTRL+""1-6"")""")
EmptyIniWrite($english, "hotkey-settings", "03", """Default (CTRL+""1 to 6"")""")
EmptyIniWrite($english, "hotkey-settings", "04", """Define a key for the input field""")
EmptyIniWrite($english, "about", "01", """About the program...""")
EmptyIniWrite($english, "download", "01", """VirtualBox Portable""")
EmptyIniWrite($english, "download", "02", """Here you can find the VirtualBox installation files, which can be automatically downloaded and make some changes, just make the settings and click ""Apply"".""")
EmptyIniWrite($english, "download", "03", """Download installation VirtualBox files""")
EmptyIniWrite($english, "download", "04", """or""")
EmptyIniWrite($english, "download", "05", """Path to VirtualBox installation file...""")
EmptyIniWrite($english, "download", "06", """Overview""")
EmptyIniWrite($english, "download", "07", """Unzip files for 32-bit systems""")
EmptyIniWrite($english, "download", "08", """Unzip files for 64-bit systems""")
EmptyIniWrite($english, "download", "09", """Compress files to reduce size""")
EmptyIniWrite($english, "download", "10", """Run VirtualBox Portable after unpack""")
EmptyIniWrite($english, "download", "11", """Status:""")
EmptyIniWrite($english, "download", "12", """Apply""")
EmptyIniWrite($english, "download", "13", """VirtualBox License""")
EmptyIniWrite($english, "download", "14", """Exit""")
EmptyIniWrite($english, "download", "15", """Info""")
EmptyIniWrite($english, "download", "16", """Please restart VirtualBox to adapt the paths""")
EmptyIniWrite($english, "status", "01", """Downloading:""")
EmptyIniWrite($english, "status", "02", """Download complete! Files are stored in the Portable-VirtualBox folder.VirtualBox - Installing files""")
EmptyIniWrite($english, "status", "03", """VirtualBox - Installing files""")
EmptyIniWrite($english, "status", "04", """Please wait, unpacking files.""")
EmptyIniWrite($english, "status", "05", """Please wait, copying files.""")
EmptyIniWrite($english, "status", "06", """Please wait, compressing files.""")
EmptyIniWrite($english, "status", "07", """Please wait, deleting files and folders""")
EmptyIniWrite($english, "status", "08", """Unpacking, copying files completed""")
EmptyIniWrite($english, "status", "09", """Please wait, backing up old files and folders.""")
EmptyIniWrite($english, "status", "10", """Please wait, downloading updates.""")
EmptyIniWrite($english, "status", "11", """Please wait, updating files and folders.""")
EmptyIniWrite($english, "status", "12", """Update complete.""")

EmptyIniWrite($french, "tray", "01", """Afficher la Machine Virtuelle""", "32")
EmptyIniWrite($french, "tray", "02", """Masquer la Machine Virtuelle""", "32")
EmptyIniWrite($french, "tray", "03", """Afficher VirtualBox""", "32")
EmptyIniWrite($french, "tray", "04", """Masquer VirtualBox""", "32")
EmptyIniWrite($french, "tray", "05", """Paramètres""", "32")
EmptyIniWrite($french, "tray", "06", """Quitter VirtualBox""", "32")
EmptyIniWrite($french, "tray", "07", """Faites un clic droit pour afficher le menu""", "32")
EmptyIniWrite($french, "messages", "01", """Erreur""", "32")
EmptyIniWrite($french, "messages", "02", """Enregistrer""", "32")
EmptyIniWrite($french, "messages", "03", """Fermer""", "32")
EmptyIniWrite($french, "messages", "04", """Enregistré""", "32")
EmptyIniWrite($french, "messages", "05", """Redémarrez VirtualBox pour prendre en compte les nouveaux paramètres.""", "32")
EmptyIniWrite($french, "messages", "06", """Démarrer Portable-VirtualBox""", "32")
EmptyIniWrite($french, "messages", "07", """Quitter Portable-VirtualBox""", "32")
EmptyIniWrite($french, "start", "01", """Copiez les fichiers depuis VirtualBox dans le dossier de l'application.""", "32")
EmptyIniWrite($french, "settings", "01", """Paramètres""", "32")
EmptyIniWrite($french, "settings", "02", """Exécution de VirtualBox avec prise en charge réseau""", "32")
EmptyIniWrite($french, "settings", "03", """Exécution de VirtualBox avec prise en charge USB""", "32")
EmptyIniWrite($french, "settings", "04", """Lancer VirtualBox avec prise en charge des raccourcis clavier de la barre d'état système""", "32")
EmptyIniWrite($french, "settings", "05", """Langue de l'interface :""", "32")
EmptyIniWrite($french, "settings", "06", """Dossier pour sauvegarder les paramètres de VirtualBox:""", "32")
EmptyIniWrite($french, "settings", "07", """Dossier pour sauvegarder les fichiers de la machine:""", "32")
EmptyIniWrite($french, "settings", "08", """Exécutez VirtualBox à partir de la machine virtuelle:""", "32")
EmptyIniWrite($french, "settings", "09", """Aperçu""", "32")
EmptyIniWrite($french, "settings", "10", """Sélectionnez le répertoire personnel""", "32")
EmptyIniWrite($french, "settings", "11", """Sélectionnez le répertoire de la machine virtuelle""", "32")
EmptyIniWrite($french, "hotkey-settings", "01", """Paramètres des raccourcis clavier""", "32")
EmptyIniWrite($french, "hotkey-settings", "02", """Vous pouvez personnaliser les raccourcis claviers sur cette page. Note: Les touches de commande sont limitées à ALT, CTRL et SHIFT. (DÉFAUT = CTRL+""1 à 6"")""", "32")
EmptyIniWrite($french, "hotkey-settings", "03", """Par défaut (CTRL+""1 à 6"")""", "32")
EmptyIniWrite($french, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "32")
EmptyIniWrite($french, "about", "01", """A propos de...""", "32")
EmptyIniWrite($french, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($french, "download", "02", """Ici vous pouvez trouver les fichiers d'installation de VirtualBox qui peuvent être téléchargés automatiquement et apporter quelques modifications, il suffit de définir les paramètres et de cliquer sur ""OK"".""", "32")
EmptyIniWrite($french, "download", "03", """Télécharger les fichiers d'installation de VirtualBox""", "32")
EmptyIniWrite($french, "download", "04", """OU""", "32")
EmptyIniWrite($french, "download", "05", """Le chemin vers les fichiers d'installation de VirtualBox est...""", "32")
EmptyIniWrite($french, "download", "06", """recherche""", "32")
EmptyIniWrite($french, "download", "07", """Extraire les fichiers pour un système 32-Bit""", "32")
EmptyIniWrite($french, "download", "08", """Extraire les fichiers pour un système 64-Bit""", "32")
EmptyIniWrite($french, "download", "09", """Compresser les fichiers afin de réduire la taille""", "32")
EmptyIniWrite($french, "download", "10", """Démarrer Portable-VirtualBox après l'extraction et / ou la compression""", "32")
EmptyIniWrite($french, "download", "11", """Informations:""", "32")
EmptyIniWrite($french, "download", "12", """OK""", "32")
EmptyIniWrite($french, "download", "13", """Licence de VirtualBox""", "32")
EmptyIniWrite($french, "download", "14", """Sortie""", "32")
EmptyIniWrite($french, "download", "15", """Info""", "32")
EmptyIniWrite($french, "download", "16", """Veuillez redémarrer Portable-Virtualbox afin de mettre à jour les chemins!""", "32")
EmptyIniWrite($french, "status", "01", """Téléchargement en cours:""", "32")
EmptyIniWrite($french, "status", "02", """Prêt pour le téléchargement! Les dossiers ont été stockés dans le dossier Portable-VirtualBox.""", "32")
EmptyIniWrite($french, "status", "03", """VirtualBox - Fichier d'installation""", "32")
EmptyIniWrite($french, "status", "04", """Extraction des fichiers en cours, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "05", """Copie des fichiers en cours, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "06", """Compression des fichiers en cours, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "07", """Suppression des fichiers et des dossiers en cours, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "08", """Fin de l’opération d’extraction, de copie ou de compression""", "32")
EmptyIniWrite($french, "status", "09", """Sauvegarde des anciens fichiers et dossiers en cours, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "10", """Téléchargement des mises à jour, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "11", """Mise à jour des fichiers et de dossiers, veuillez patienter.""", "32")
EmptyIniWrite($french, "status", "12", """Mise à jour terminée.""", "32")

EmptyIniWrite($german, "tray", "01", """Zeige VM""", "32")
EmptyIniWrite($german, "tray", "02", """Verstecke VM""", "32")
EmptyIniWrite($german, "tray", "03", """Zeige VirtualBox""", "32")
EmptyIniWrite($german, "tray", "04", """Verstecke VirtualBox""", "32")
EmptyIniWrite($german, "tray", "05", """Einstellungen""", "32")
EmptyIniWrite($german, "tray", "06", """Beende VirtualBox""", "32")
EmptyIniWrite($german, "tray", "07", """Rechts-Klick, um Menü zu sehen""", "32")
EmptyIniWrite($german, "messages", "01", """Fehler""", "32")
EmptyIniWrite($german, "messages", "02", """Speichern""", "32")
EmptyIniWrite($german, "messages", "03", """Beenden""", "32")
EmptyIniWrite($german, "messages", "04", """Gespeichert""", "32")
EmptyIniWrite($german, "messages", "05", """VirtualBox neustarten, um die Einstellungen zu übernehmen.""", "32")
EmptyIniWrite($german, "messages", "06", """Starte Portable-VirtualBox""", "32")
EmptyIniWrite($german, "messages", "07", """Beende Portable-VirtualBox""", "32")
EmptyIniWrite($german, "start", "01", """Die Dateien von VirtualBox in den (jeweiligen) APP-ORDNER kopieren.""", "32")
EmptyIniWrite($german, "settings", "01", """Einstellungen""", "32")
EmptyIniWrite($german, "settings", "02", """Ausführen von VirtualBox mit Netzwerkunterstützung""", "32")
EmptyIniWrite($german, "settings", "03", """Ausführen von VirtualBox mit USB-Unterstützung""", "32")
EmptyIniWrite($german, "settings", "04", """Starten Sie VirtualBox mit Tray-Hotkey-Unterstützung""", "32")
EmptyIniWrite($german, "settings", "05", """Schnittstellensprache:""", "32")
EmptyIniWrite($german, "settings", "06", """Ordner zum Speichern der VirtualBox-Einstellungen:""", "32")
EmptyIniWrite($german, "settings", "07", """Ordner zum Speichern von Maschinendateien:""", "32")
EmptyIniWrite($german, "settings", "08", """Führen Sie VirtualBox von der VM aus:""", "32")
EmptyIniWrite($german, "settings", "09", """Rezension""", "32")
EmptyIniWrite($german, "settings", "10", """Home-Verzeichnis auswählen""", "32")
EmptyIniWrite($german, "settings", "11", """VM-Verzeichnis auswählen""", "32")
EmptyIniWrite($german, "hotkey-settings", "01", """HotKey-Einstellungen""", "32")
EmptyIniWrite($german, "hotkey-settings", "02", """Falls dir die Standardeinstellungen der HotKeys nicht zusagen, ist es hier möglich, eigene Tastenkombinationen zu definieren. Hinweis: Die Steuertasten beschränken sich auf ALT, CTRL und SHIFT, die letzte Taste ist frei definierbar. (DEFAULT = STRG+""1-6"")""", "32")
EmptyIniWrite($german, "hotkey-settings", "03", """DEFAULT (STRG+""1 bis 6"")""", "32")
EmptyIniWrite($german, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "32")
EmptyIniWrite($german, "about", "01", """Über das Programm...""", "32")
EmptyIniWrite($german, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($german, "download", "02", """Hier kannst du die Installationsdateien von VirtualBox automatisch herunterladen lassen und einige Einstellungen vornehmen (Wenn du VirtualBox mit diesem Skript herunterlädst, nur noch die Einstellungen vornehmen und auf ""OK"" klicken).""", "32")
EmptyIniWrite($german, "download", "03", """Installations dateien von VirtualBox herunterladen""", "32")
EmptyIniWrite($german, "download", "04", """ODER""", "32")
EmptyIniWrite($german, "download", "05", """Pfad zu der Installationsdatei von VirtualBox ist...""", "32")
EmptyIniWrite($german, "download", "06", """Rezension""", "32")
EmptyIniWrite($german, "download", "07", """Extrahieren Sie die Dateien für ein 32-Bit-System""", "32")
EmptyIniWrite($german, "download", "08", """Extrahieren Sie die Dateien für ein 64-Bit-System""", "32")
EmptyIniWrite($german, "download", "09", """Komprimiere die Dateien, um Platz zu sparen""", "32")
EmptyIniWrite($german, "download", "10", """Starten VirtualBox Portable nach dem Entpacken""", "32")
EmptyIniWrite($german, "download", "11", """Status-Info:""", "32")
EmptyIniWrite($german, "download", "12", """OK""", "32")
EmptyIniWrite($german, "download", "13", """Lizenz VirtualBox""", "32")
EmptyIniWrite($german, "download", "14", """Ausfahrt""", "32")
EmptyIniWrite($german, "download", "15", """Info""", "32")
EmptyIniWrite($german, "download", "16", """Bitte starten Sie VirtualBox neu, um die Pfade anzupassen!""", "32")
EmptyIniWrite($german, "status", "01", """Herunterladen:""", "32")
EmptyIniWrite($german, "status", "02", """Fertig mit dem Herunterladen! Die Dateien wurden im Portable-VirtualBox Ordner gespeichert.""", "32")
EmptyIniWrite($german, "status", "03", """VirtualBox - Installationsdatei""", "32")
EmptyIniWrite($german, "status", "04", """Bitte warten, entpacke Dateien.""", "32")
EmptyIniWrite($german, "status", "05", """Bitte warten, kopiere Dateien.""", "32")
EmptyIniWrite($german, "status", "06", """Bitte warten, packe Dateien.""", "32")
EmptyIniWrite($german, "status", "07", """Bitte warten, lösche Dateien und Ordner.""", "32")
EmptyIniWrite($german, "status", "08", """Fertig, mit entpacken und/oder packen und kopieren der Dateien.""", "32")
EmptyIniWrite($german, "status", "09", """Bitte warten, sichern der alten Dateien und Ordner.""", "32")
EmptyIniWrite($german, "status", "10", """Bitte warten, UpDate herunterladen.""", "32")
EmptyIniWrite($german, "status", "11", """Bitte warten, aktualisiere Dateien und Ordner.""", "32")
EmptyIniWrite($german, "status", "12", """Fertig, mit dem UpDate.""", "32")

EmptyIniWrite($italian, "tray", "01", """Mostra VM""", "32")
EmptyIniWrite($italian, "tray", "02", """Nascondi VM""", "32")
EmptyIniWrite($italian, "tray", "03", """Mostra VirtualBox""", "32")
EmptyIniWrite($italian, "tray", "04", """Nascondi VirtualBox""", "32")
EmptyIniWrite($italian, "tray", "05", """Impostazioni""", "32")
EmptyIniWrite($italian, "tray", "06", """Esci da VirtualBox""", "32")
EmptyIniWrite($italian, "tray", "07", """Destro del mouse per vedere il menu""", "32")
EmptyIniWrite($italian, "messages", "01", """Errore""", "32")
EmptyIniWrite($italian, "messages", "02", """Salva""", "32")
EmptyIniWrite($italian, "messages", "03", """Vicina""", "32")
EmptyIniWrite($italian, "messages", "04", """Salvato""", "32")
EmptyIniWrite($italian, "messages", "05", """Riavvia VirtualBox per applicare le impostazioni.""", "32")
EmptyIniWrite($italian, "messages", "06", """Avvio di VirtualBox""", "32")
EmptyIniWrite($italian, "messages", "07", """Chiusura di VirtualBox""", "32")
EmptyIniWrite($italian, "start", "01", """Copia i file da VirtualBox nel rispettivo APP-Folder.""", "32")
EmptyIniWrite($italian, "settings", "01", """Impostazioni""", "32")
EmptyIniWrite($italian, "settings", "02", """Esecuzione di VirtualBox con supporto di rete""", "32")
EmptyIniWrite($italian, "settings", "03", """Esecuzione di VirtualBox con supporto USB""", "32")
EmptyIniWrite($italian, "settings", "04", """Avvia VirtualBox con il supporto dei tasti di scelta rapida nella barra delle applicazioni""", "32")
EmptyIniWrite($italian, "settings", "05", """Lingua dell'interfaccia:""", "32")
EmptyIniWrite($italian, "settings", "06", """Cartella per salvare le impostazioni di VirtualBox:""", "32")
EmptyIniWrite($italian, "settings", "07", """Cartella per salvare i file della macchina:""", "32")
EmptyIniWrite($italian, "settings", "08", """Eseguire VirtualBox dalla VM:""", "32")
EmptyIniWrite($italian, "settings", "09", """Seleziona""", "32")
EmptyIniWrite($italian, "settings", "10", """Seleziona la directory home""", "32")
EmptyIniWrite($italian, "settings", "11", """Seleziona la directory della VM""", "32")
EmptyIniWrite($italian, "hotkey-settings", "01", """Imposta HotKeys""", "32")
EmptyIniWrite($italian, "hotkey-settings", "02", """Per specificare hotkeys diversi da quelli predefiniti, farlo quì. Nota: I tasti di comando sono limitati a Alt, Ctrl e Shift. L'ultimo tasto e autodefinito. (Predefinito: CTRL+""1-6"")""", "32")
EmptyIniWrite($italian, "hotkey-settings", "03", """DPredefinito (CTRL+""1..6"")""", "32")
EmptyIniWrite($italian, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "32")
EmptyIniWrite($italian, "about", "01", """A proposito del programma...""", "32")
EmptyIniWrite($italian, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($italian, "download", "02", """Qui potete trovare i file di installazione di VirtualBox può scaricare automaticamente ed effettuare alcune regolazioni (Se si utilizza questo script scaricare VirtualBox, solo effettuare le impostazioni e fare clic su ""OK"").""", "32")
EmptyIniWrite($italian, "download", "03", """Scaricare file di installazione di VirtualBox""", "32")
EmptyIniWrite($italian, "download", "04", """O""", "32")
EmptyIniWrite($italian, "download", "05", """Percorso del file di installazione di VirtualBox è...""", "32")
EmptyIniWrite($italian, "download", "06", """Seleziona""", "32")
EmptyIniWrite($italian, "download", "07", """Estrarre i file da un sistema a 32-Bit""", "32")
EmptyIniWrite($italian, "download", "08", """Estrarre i file da un sistema a 64-Bit""", "32")
EmptyIniWrite($italian, "download", "09", """Comprimere i file per ridurre le dimensioni""", "32")
EmptyIniWrite($italian, "download", "10", """Avvia VirtualBox Portable dopo aver decompresso""", "32")
EmptyIniWrite($italian, "download", "11", """Informazione-stato:""", "32")
EmptyIniWrite($italian, "download", "12", """OK""", "32")
EmptyIniWrite($italian, "download", "13", """Licenza di VirtualBox""", "32")
EmptyIniWrite($italian, "download", "14", """Uscita""", "32")
EmptyIniWrite($italian, "download", "15", """Info""", "32")
EmptyIniWrite($italian, "download", "16", """Si prega di avviare VirtualBox di nuovo, in modo che tutti i percorsi possono essere adattati!""", "32")
EmptyIniWrite($italian, "status", "01", """Il download:""", "32")
EmptyIniWrite($italian, "status", "02", """Pronti con il download! Il file è stato memorizzato nella cartella-Portable VirtualBox.""", "32")
EmptyIniWrite($italian, "status", "03", """VirtualBox - Installazione Faldone.""", "32")
EmptyIniWrite($italian, "status", "04", """Attendere, estrarre i file.""", "32")
EmptyIniWrite($italian, "status", "05", """Attendere prego, copiare i file.""", "32")
EmptyIniWrite($italian, "status", "06", """Attendere, comprimere i file.""", "32")
EmptyIniWrite($italian, "status", "07", """Attendere prego, eliminare file e cartelle.""", "32")
EmptyIniWrite($italian, "status", "08", """Finito, estratti e / o di comprimere e copiare i file.""", "32")
EmptyIniWrite($italian, "status", "09", """Attendere prego, fare backup dei vecchi file e cartelle""", "32")
EmptyIniWrite($italian, "status", "10", """Attendere, scaricare l'aggiornamento.""", "32")
EmptyIniWrite($italian, "status", "11", """Attendere prego, aggiornare i file e cartelle.""", "32")
EmptyIniWrite($italian, "status", "12", """Finito, l'aggiornamento.""", "32")

EmptyIniWrite($japanese, "tray", "01", """VM を表示""", "32")
EmptyIniWrite($japanese, "tray", "02", """VM を隠す""", "32")
EmptyIniWrite($japanese, "tray", "03", """VirtualBox を表示""", "32")
EmptyIniWrite($japanese, "tray", "04", """VirtualBox を隠す""", "32")
EmptyIniWrite($japanese, "tray", "05", """設定""", "32")
EmptyIniWrite($japanese, "tray", "06", """VirtualBoxを終了""", "32")
EmptyIniWrite($japanese, "tray", "07", """右クリックでメニューを表示""", "32")
EmptyIniWrite($japanese, "messages", "01", """エラー""", "32")
EmptyIniWrite($japanese, "messages", "02", """保存""", "32")
EmptyIniWrite($japanese, "messages", "03", """近い""", "32")
EmptyIniWrite($japanese, "messages", "04", """保存されました""", "32")
EmptyIniWrite($japanese, "messages", "05", """設定を変更するには、VirtualBox を再起動します。""", "32")
EmptyIniWrite($japanese, "messages", "06", """Portable-VirtualBox を起動します""", "32")
EmptyIniWrite($japanese, "messages", "07", """Portable-VirtualBox を終了します""", "32")
EmptyIniWrite($japanese, "start", "01", """VirtualBox からファイルをそれぞれの APP-Folder にコピーします。""", "32")
EmptyIniWrite($japanese, "settings", "01", """設定""", "32")
EmptyIniWrite($japanese, "settings", "02", """ネットワークサポート付きのVirtualBoxの実行""", "32")
EmptyIniWrite($japanese, "settings", "03", """USBサポートでVirtualBoxを実行する""", "32")
EmptyIniWrite($japanese, "settings", "04", """トレイホットキーサポートでVirtualBoxを起動する""", "32")
EmptyIniWrite($japanese, "settings", "05", """インターフェース言語:""", "32")
EmptyIniWrite($japanese, "settings", "06", """VirtualBox設定を保存するフォルダ:""", "32")
EmptyIniWrite($japanese, "settings", "07", """マシンファイルを保存するフォルダ:""", "32")
EmptyIniWrite($japanese, "settings", "08", """VM から VirtualBox を実行します。""", "32")
EmptyIniWrite($japanese, "settings", "09", """レビュー""", "32")
EmptyIniWrite($japanese, "settings", "10", """ホームディレクトリを選択""", "32")
EmptyIniWrite($japanese, "settings", "11", """VMディレクトリを選択""", "32")
EmptyIniWrite($japanese, "hotkey-settings", "01", """ホットキーの設定""", "32")
EmptyIniWrite($japanese, "hotkey-settings", "02", """プリセット以外のホットキーを選択するには、ここに独自のコマンドを指定します。注: コマンドキーは ALT 、CTRL 、SHIFT に制限されています。最後のキーは自己定義です。(デフォルト = CTRL+""1-6"")""", "32")
EmptyIniWrite($japanese, "hotkey-settings", "03", """デフォルト (CTRL+""1 to 6"")""", "32")
EmptyIniWrite($japanese, "hotkey-settings", "04", """入力フィールドのキーを定義する""", "32")
EmptyIniWrite($japanese, "about", "01", """プログラムについて...""", "32")
EmptyIniWrite($japanese, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($japanese, "download", "02", """VirtualBox のインストールファイルを自動でダウンロードしていくつかの調整を行います。(このスクリプトを使用して VirtualBox をダウンロードする場合、設定では ""OK"" をクリックするだけにします)""", "32")
EmptyIniWrite($japanese, "download", "03", """VirtualBox インストールファイルのダウンロード""", "32")
EmptyIniWrite($japanese, "download", "04", """または""", "32")
EmptyIniWrite($japanese, "download", "05", """VirtualBox インストールファイルのパス...""", "32")
EmptyIniWrite($japanese, "download", "06", """検索""", "32")
EmptyIniWrite($japanese, "download", "07", """32 ビットシステム用のファイルを展開します""", "32")
EmptyIniWrite($japanese, "download", "08", """64 ビットシステム用のファイルを展開します""", "32")
EmptyIniWrite($japanese, "download", "09", """サイズを小さくするためにファイルを圧縮""", "32")
EmptyIniWrite($japanese, "download", "10", """展開 および / または 圧縮の後、Portable-VirtualBox を起動""", "32")
EmptyIniWrite($japanese, "download", "11", """ステータス情報:""", "32")
EmptyIniWrite($japanese, "download", "12", """OK""", "32")
EmptyIniWrite($japanese, "download", "13", """ライセンス VirtualBox""", "32")
EmptyIniWrite($japanese, "download", "14", """出口""", "32")
EmptyIniWrite($japanese, "download", "15", """情報""", "32")
EmptyIniWrite($japanese, "download", "16", """VirtualBox を再起動してパスを適応させます。""", "32")
EmptyIniWrite($japanese, "status", "01", """ダウンロード中:""", "32")
EmptyIniWrite($japanese, "status", "02", """ダウンロード終了! ファイルは Portable-VirtualBox フォルダに保存されています。""", "32")
EmptyIniWrite($japanese, "status", "03", """VirtualBox - インストールファイル""", "32")
EmptyIniWrite($japanese, "status", "04", """お待ちください、ファイルの展開中。""", "32")
EmptyIniWrite($japanese, "status", "05", """お待ちください、ファイルのコピー中""", "32")
EmptyIniWrite($japanese, "status", "06", """お待ちください、ファイルの圧縮中。""", "32")
EmptyIniWrite($japanese, "status", "07", """お待ちください、ファイルおよびフォルダの削除中""", "32")
EmptyIniWrite($japanese, "status", "08", """完了、ファイルの展開 および / または 圧縮、そしてコピー。""", "32")
EmptyIniWrite($japanese, "status", "09", """しばらくお待ちください、古いファイルとフォルダのバックアップを作成しています。""", "32")
EmptyIniWrite($japanese, "status", "10", """お待ちください、アップデートをダウンロード中。""", "32")
EmptyIniWrite($japanese, "status", "11", """しばらくお待ちください、ファイルやフォルダを更新しています。""", "32")
EmptyIniWrite($japanese, "status", "12", """完了、アップデート。""", "32")

EmptyIniWrite($korean, "tray", "01", """VM 보이기""", "32")
EmptyIniWrite($korean, "tray", "02", """VM 숨기기""", "32")
EmptyIniWrite($korean, "tray", "03", """VirtualBox 보이기""", "32")
EmptyIniWrite($korean, "tray", "04", """VirtualBox 숨기기""", "32")
EmptyIniWrite($korean, "tray", "05", """설정""", "32")
EmptyIniWrite($korean, "tray", "06", """VirtualBox 종료""", "32")
EmptyIniWrite($korean, "tray", "07", """메뉴를 보려면 마우스 오른쪽 버튼을 클릭하세요""", "32")
EmptyIniWrite($korean, "messages", "01", """오류""", "32")
EmptyIniWrite($korean, "messages", "02", """저장""", "32")
EmptyIniWrite($korean, "messages", "03", """닫다""", "32")
EmptyIniWrite($korean, "messages", "04", """저장됨""", "32")
EmptyIniWrite($korean, "messages", "05", """설정을 변경하려면 VirtualBox를 다시 시작하세요.""", "32")
EmptyIniWrite($korean, "messages", "06", """Portable-VirtualBox 시작""", "32")
EmptyIniWrite($korean, "messages", "07", """Portable-VirtualBox 나가기""", "32")
EmptyIniWrite($korean, "start", "01", """VirtualBox의 파일을 APP 디렉터리의 해당 폴더에 복사합니다.""", "32")
EmptyIniWrite($korean, "settings", "01", """설정""", "32")
EmptyIniWrite($korean, "settings", "02", """네트워크 지원을 통한 VirtualBox 실행""", "32")
EmptyIniWrite($korean, "settings", "03", """USB 지원을 통한 VirtualBox 실행""", "32")
EmptyIniWrite($korean, "settings", "04", """트레이 단축키 지원을 통해 VirtualBox 실행""", "32")
EmptyIniWrite($korean, "settings", "05", """인터페이스 언어:""", "32")
EmptyIniWrite($korean, "settings", "06", """VirtualBox 설정을 저장하는 폴더:""", "32")
EmptyIniWrite($korean, "settings", "07", """머신 파일을 저장하는 폴더:""", "32")
EmptyIniWrite($korean, "settings", "08", """VM에서 VirtualBox 실행:""", "32")
EmptyIniWrite($korean, "settings", "09", """검토""", "32")
EmptyIniWrite($korean, "settings", "10", """홈 디렉토리 선택""", "32")
EmptyIniWrite($korean, "settings", "11", """VM 디렉토리 선택""", "32")
EmptyIniWrite($korean, "hotkey-settings", "01", """단축키-설정""", "32")
EmptyIniWrite($korean, "hotkey-settings", "02", """사전 설정보다 다른 단축키를 선택하려면, 여기에서 직접 명령을 지정하세요. 참고: 명령 키는 ALT, CTRL 및 SHIFT로 제한됩니다. 마지막 키는 자체 정의됩니다. (기본값 = CTRL+""1-6"")""", "32")
EmptyIniWrite($korean, "hotkey-settings", "03", """기본값 (CTRL+""1부터 6까지"")""", "32")
EmptyIniWrite($korean, "hotkey-settings", "04", """입력 필드에 대한 키를 정의합니다""", "32")
EmptyIniWrite($korean, "about", "01", """프로그램에 대해...""", "32")
EmptyIniWrite($korean, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($korean, "download", "02", """여기서 자동으로 다운로드하여 약간 조정할 수 있도록 할 수 있는 VirtualBox의 설치 파일을 찾을 수 있습니다 (이 스크립트를 사용하여 VirtualBox를 다운로드하는 경우, 오직 설정을 만들고 ""확인""을 클릭하세요).""", "32")
EmptyIniWrite($korean, "download", "03", """VirtualBox의 설치 파일 다운로드""", "32")
EmptyIniWrite($korean, "download", "04", """또는""", "32")
EmptyIniWrite($korean, "download", "05", """VirtualBox의 설치 파일의 경로는...""", "32")
EmptyIniWrite($korean, "download", "06", """검색""", "32")
EmptyIniWrite($korean, "download", "07", """32-비트 시스템을 위한 파일의 압축 풀기""", "32")
EmptyIniWrite($korean, "download", "08", """64-비트 시스템을 위한 파일의 압축 풀기""", "32")
EmptyIniWrite($korean, "download", "09", """크기를 줄이기 위해 파일을 압축하기""", "32")
EmptyIniWrite($korean, "download", "10", """압축 풀기 및/또는 압축하고 나서 Portable-VirtualBox 시작""", "32")
EmptyIniWrite($korean, "download", "11", """상태-정보:""", "32")
EmptyIniWrite($korean, "download", "12", """확인""", "32")
EmptyIniWrite($korean, "download", "13", """라이센스 VirtualBox""", "32")
EmptyIniWrite($korean, "download", "14", """나가기""", "32")
EmptyIniWrite($korean, "download", "15", """정보""", "32")
EmptyIniWrite($korean, "download", "16", """모든 경로를 적용할 수 있도록, VirtualBox를 다시 시작해주세요!""", "32")
EmptyIniWrite($korean, "status", "01", """다운로드 중:""", "32")
EmptyIniWrite($korean, "status", "02", """다운로드가 완료되었습니다! 파일은 Portable-VirtualBox 폴더에 저장됩니다.""", "32")
EmptyIniWrite($korean, "status", "03", """VirtualBox - 파일 설치""", "32")
EmptyIniWrite($korean, "status", "04", """기다려 주세요, 파일의 압축을 풉니다.""", "32")
EmptyIniWrite($korean, "status", "05", """기다려 주세요, 파일을 복사합니다.""", "32")
EmptyIniWrite($korean, "status", "06", """기다려 주세요, 파일을 압축합니다.""", "32")
EmptyIniWrite($korean, "status", "07", """기다려 주세요, 파일 및 폴더를 삭제합니다.""", "32")
EmptyIniWrite($korean, "status", "08", """파일 압축 풀기 및/또는 압축 및 복사를 마쳤습니다.""", "32")
EmptyIniWrite($korean, "status", "09", """기다려 주세요, 오래된 파일 및 폴더의 백업을 만듭니다.""", "32")
EmptyIniWrite($korean, "status", "10", """기다려 주세요, 업데이트를 다운로드합니다.""", "32")
EmptyIniWrite($korean, "status", "11", """기다려 주세요, 파일 및 폴더를 업데이트합니다.""", "32")
EmptyIniWrite($korean, "status", "12", """업데이트를 마쳤습니다.""", "32")

EmptyIniWrite($polish, "tray", "01", """Pokaż VM""", "32")
EmptyIniWrite($polish, "tray", "02", """Ukryj VM""", "32")
EmptyIniWrite($polish, "tray", "03", """Pokaż VirtualBox""", "32")
EmptyIniWrite($polish, "tray", "04", """Ukryj VirtualBox""", "32")
EmptyIniWrite($polish, "tray", "05", """Ustawienia""", "32")
EmptyIniWrite($polish, "tray", "06", """Wyjdź VirtualBox""", "32")
EmptyIniWrite($polish, "tray", "07", """Prawy klik by zobaczyć menu!""", "32")
EmptyIniWrite($polish, "messages", "01", """Błąd""", "32")
EmptyIniWrite($polish, "messages", "02", """Ratować""", "32")
EmptyIniWrite($polish, "messages", "03", """Zamknąć""", "32")
EmptyIniWrite($polish, "messages", "04", """Zapisane""", "32")
EmptyIniWrite($polish, "messages", "05", """Restartuj VirtualBox by zmienić ustawienia.""", "32")
EmptyIniWrite($polish, "messages", "06", """Uruchamiam Portable-VirtualBox""", "32")
EmptyIniWrite($polish, "messages", "07", """Zamykanie VirtualBoxa""", "32")
EmptyIniWrite($polish, "start", "01", """Kopiuj pliki z VirtualBox do folederu APP-Folder.""", "32")
EmptyIniWrite($polish, "settings", "01", """Ustawienia""", "32")
EmptyIniWrite($polish, "settings", "02", """Uruchamianie VirtualBox z obsługą sieci""", "32")
EmptyIniWrite($polish, "settings", "03", """Uruchamianie VirtualBox z obsługą USB""", "32")
EmptyIniWrite($polish, "settings", "04", """Uruchom VirtualBox z obsługą skrótu klawiszowego w zasobniku""", "32")
EmptyIniWrite($polish, "settings", "05", """Język interfejsu:""", "32")
EmptyIniWrite($polish, "settings", "06", """Folder do zapisywania ustawień VirtualBox:""", "32")
EmptyIniWrite($polish, "settings", "07", """Folder do zapisywania plików maszynowych:""", "32")
EmptyIniWrite($polish, "settings", "08", """Uruchom VirtualBox z maszyny wirtualnej:""", "32")
EmptyIniWrite($polish, "settings", "09", """Recenzja""", "32")
EmptyIniWrite($polish, "settings", "10", """Wybierz katalog domowy""", "32")
EmptyIniWrite($polish, "settings", "11", """Wybierz katalog maszyny wirtualnej""", "32")
EmptyIniWrite($polish, "hotkey-settings", "01", """Ustawienia-HotKey""", "32")
EmptyIniWrite($polish, "hotkey-settings", "02", """Żeby wybrać HotKey, ustaw komendy tutaj. Uwaga: Komendy przycisków limitowane do ALT, CTRL i SHIFT. Ostatni przycisk definiowany przez użytkownika. (DOMYŚLNIE = CTRL+""1-6"")""", "32")
EmptyIniWrite($polish, "hotkey-settings", "03", """DOMYŚLNE (CTRL+""1 to 6"")""", "32")
EmptyIniWrite($polish, "hotkey-settings", "04", """Zdefiniuj klucz dla pola wejściowego""", "32")
EmptyIniWrite($polish, "about", "01", """O programie...""", "32")
EmptyIniWrite($polish, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($polish, "download", "02", """Tutaj można znaleźć pliki instalacyjne z VirtualBox może automatycznie pobierać i dokonać pewnych korekt (Jeżeli używasz tego skryptu pobierania VirtualBox, zaznacz te ustawienia i kliknij przycisk ""OK"").""", "32")
EmptyIniWrite($polish, "download", "03", """Pobierz pliki instalacyjne VirtualBox""", "32")
EmptyIniWrite($polish, "download", "04", """LUB""", "32")
EmptyIniWrite($polish, "download", "05", """Ścieżka pliku instalacyjnego VirtualBox...""", "32")
EmptyIniWrite($polish, "download", "06", """Szukaj""", "32")
EmptyIniWrite($polish, "download", "07", """Wypakuj pliki dla 32-bit systemu""", "32")
EmptyIniWrite($polish, "download", "08", """Wypakuj pliki dla 64-bit systemu""", "32")
EmptyIniWrite($polish, "download", "09", """Spakuj pliki by zredukować wielkość""", "32")
EmptyIniWrite($polish, "download", "10", """Uruchom Portable-VirtualBox po wypakowaniu""", "32")
EmptyIniWrite($polish, "download", "11", """Status-Info:""", "32")
EmptyIniWrite($polish, "download", "12", """OK""", "32")
EmptyIniWrite($polish, "download", "13", """Licencja VirtualBox""", "32")
EmptyIniWrite($polish, "download", "14", """Wyjście""", "32")
EmptyIniWrite($polish, "download", "15", """Info""", "32")
EmptyIniWrite($polish, "download", "16", """Proszę uruchomić VirtualBox ponownie, nowe pliki zostaną adoptowane!""", "32")
EmptyIniWrite($polish, "status", "01", """Załadunek:""", "32")
EmptyIniWrite($polish, "status", "02", """Pobieranie zakończone! Pliki są przechowywane w folderze Portable-VirtualBox.""", "32")
EmptyIniWrite($polish, "status", "03", """VirtualBox - Instalacja plików""", "32")
EmptyIniWrite($polish, "status", "04", """Proszę czekać, pliki się rozpakowują.""", "32")
EmptyIniWrite($polish, "status", "05", """Proszę czekać, pliki są kopiowane.""", "32")
EmptyIniWrite($polish, "status", "06", """Proszę czekać, kompresja pliku.""", "32")
EmptyIniWrite($polish, "status", "07", """Proszę czekać, usuwanie plików i folderów""", "32")
EmptyIniWrite($polish, "status", "08", """Rozpakowanie, kopiowanie plików zakończone""", "32")
EmptyIniWrite($polish, "status", "09", """Poczekaj, wykonaj kopię zapasową starych plików i folderów.""", "32")
EmptyIniWrite($polish, "status", "10", """Proszę czekać, pobieranie aktualizacji.""", "32")
EmptyIniWrite($polish, "status", "11", """Proszę czekać, aktualizuję pliki i foldery.""", "32")
EmptyIniWrite($polish, "status", "12", """Aktualizacja została ukończona.""", "32")

EmptyIniWrite($portuguese, "tray", "01", """Mostrar VM""", "32")
EmptyIniWrite($portuguese, "tray", "02", """Ocultar VM""", "32")
EmptyIniWrite($portuguese, "tray", "03", """Mostrar VirtualBox""", "32")
EmptyIniWrite($portuguese, "tray", "04", """Ocultar VirtualBox""", "32")
EmptyIniWrite($portuguese, "tray", "05", """Ajustes""", "32")
EmptyIniWrite($portuguese, "tray", "06", """Saindo do VirtualBox""", "32")
EmptyIniWrite($portuguese, "tray", "07", """Botão direito do mouse para ver o menu""", "32")
EmptyIniWrite($portuguese, "messages", "01", """Erro""", "32")
EmptyIniWrite($portuguese, "messages", "02", """Salvar""", "32")
EmptyIniWrite($portuguese, "messages", "03", """Fechar""", "32")
EmptyIniWrite($portuguese, "messages", "04", """Conservado""", "32")
EmptyIniWrite($portuguese, "messages", "05", """Reinicie o VirtualBox para alterar as configurações.""", "32")
EmptyIniWrite($portuguese, "messages", "06", """Iniciando o VirtualBox""", "32")
EmptyIniWrite($portuguese, "messages", "07", """Sair VirtualBox-Portable""", "32")
EmptyIniWrite($portuguese, "start", "01", """Copie as limas de VirtualBox (respectivo) no APP-Dobrador.""", "32")
EmptyIniWrite($portuguese, "settings", "01", """Configurações""", "32")
EmptyIniWrite($portuguese, "settings", "02", """Executando o VirtualBox com suporte de rede""", "32")
EmptyIniWrite($portuguese, "settings", "03", """Executando o VirtualBox com suporte USB""", "32")
EmptyIniWrite($portuguese, "settings", "04", """Inicie o VirtualBox com suporte para teclas de atalho na bandeja""", "32")
EmptyIniWrite($portuguese, "settings", "05", """Linguagem da interface:""", "32")
EmptyIniWrite($portuguese, "settings", "06", """Pasta para salvar as configurações do VirtualBox:""", "32")
EmptyIniWrite($portuguese, "settings", "07", """Pasta para salvar arquivos da máquina:""", "32")
EmptyIniWrite($portuguese, "settings", "08", """Execute o VirtualBox a partir da VM:""", "32")
EmptyIniWrite($portuguese, "settings", "09", """Análise""", "32")
EmptyIniWrite($portuguese, "settings", "10", """Selecione o diretório inicial""", "32")
EmptyIniWrite($portuguese, "settings", "11", """Selecione o diretório da VM""", "32")
EmptyIniWrite($portuguese, "hotkey-settings", "01", """HotKey-Ajustes""", "32")
EmptyIniWrite($portuguese, "hotkey-settings", "02", """Aqui você pode alterar os valores das teclas de atalho. Nota: Você pode usar as teclas ALT, CTRL e SHIFT. (PADRÃO = CTRL+""1-6"")""", "32")
EmptyIniWrite($portuguese, "hotkey-settings", "03", """POR PADRÃO (CTRL+""1 a 6"")""", "32")
EmptyIniWrite($portuguese, "hotkey-settings", "04", """Defina uma chave para o campo de entrada""", "32")
EmptyIniWrite($portuguese, "about", "01", """Sobre o programa...""", "32")
EmptyIniWrite($portuguese, "download", "01", """VirtualBox Portable""", "32")
EmptyIniWrite($portuguese, "download", "02", """Aqui pode encontrar os arquivos de instalação do VirtualBox pode automaticamente fazer o download e fazer alguns ajustes (Se você usar este script baixar o VirtualBox, só fazer as configurações e clique em ""OK"").""", "32")
EmptyIniWrite($portuguese, "download", "03", """Baixe os arquivos de instalação do VirtualBox""", "32")
EmptyIniWrite($portuguese, "download", "04", """OU""", "32")
EmptyIniWrite($portuguese, "download", "05", """Caminho para o arquivo de instalação do VirtualBox é...""", "32")
EmptyIniWrite($portuguese, "download", "06", """Pesquisa""", "32")
EmptyIniWrite($portuguese, "download", "07", """Extraia os arquivos para um sistema de 32 bits""", "32")
EmptyIniWrite($portuguese, "download", "08", """Extraia os arquivos para um sistema de 64 bits""", "32")
EmptyIniWrite($portuguese, "download", "09", """Compactar os arquivos para reduzir o tamanho""", "32")
EmptyIniWrite($portuguese, "download", "10", """Inicie o VirtualBox Portable após descompactar""", "32")
EmptyIniWrite($portuguese, "download", "11", """Status-Info:""", "32")
EmptyIniWrite($portuguese, "download", "12", """OK""", "32")
EmptyIniWrite($portuguese, "download", "13", """Licença VirtualBox""", "32")
EmptyIniWrite($portuguese, "download", "14", """Saída""", "32")
EmptyIniWrite($portuguese, "download", "15", """Info""", "32")
EmptyIniWrite($portuguese, "download", "16", """Reinicie o VirtualBox para adaptar os caminhos!""", "32")
EmptyIniWrite($portuguese, "status", "01", """Carregando:""", "32")
EmptyIniWrite($portuguese, "status", "02", """Download concluído! Os arquivos são armazenados na pasta Portable-VirtualBox.""", "32")
EmptyIniWrite($portuguese, "status", "03", """VirtualBox - Instalando arquivos""", "32")
EmptyIniWrite($portuguese, "status", "04", """Aguarde, os arquivos estão sendo descompactados.""", "32")
EmptyIniWrite($portuguese, "status", "05", """Aguarde, os arquivos estão sendo copiados.""", "32")
EmptyIniWrite($portuguese, "status", "06", """Aguarde, compactação de arquivo.""", "32")
EmptyIniWrite($portuguese, "status", "07", """Aguarde, excluindo arquivos e pastas""", "32")
EmptyIniWrite($portuguese, "status", "08", """Descompactação, cópia de arquivos concluída""", "32")
EmptyIniWrite($portuguese, "status", "09", """Espere, faça backup de arquivos e pastas antigos.""", "32")
EmptyIniWrite($portuguese, "status", "10", """Aguarde, baixando atualizações.""", "32")
EmptyIniWrite($portuguese, "status", "11", """Aguarde, atualizando arquivos e pastas.""", "32")
EmptyIniWrite($portuguese, "status", "12", """A atualização está completa.""", "32")

EmptyIniWrite($russian, "tray", "01", """Показать VM""", "512")
EmptyIniWrite($russian, "tray", "02", """Скрыть VM""", "512")
EmptyIniWrite($russian, "tray", "03", """Показать VirtualBox""", "512")
EmptyIniWrite($russian, "tray", "04", """Скрыть VirtualBox""", "512")
EmptyIniWrite($russian, "tray", "05", """Настройки""", "512")
EmptyIniWrite($russian, "tray", "06", """Выход из VirtualBox""", "512")
EmptyIniWrite($russian, "tray", "07", """Щелкните правой кнопкой мыши, чтобы увидеть меню""", "512")
EmptyIniWrite($russian, "messages", "01", """Ошибка""", "512")
EmptyIniWrite($russian, "messages", "02", """Сохранить""", "512")
EmptyIniWrite($russian, "messages", "03", """Закрыть""", "512")
EmptyIniWrite($russian, "messages", "04", """Сохранено""", "512")
EmptyIniWrite($russian, "messages", "05", """Перезапустите VirtualBox, чтобы изменить настройки.""", "512")
EmptyIniWrite($russian, "messages", "06", """Запуск VirtualBox""", "512")
EmptyIniWrite($russian, "messages", "07", """Закрытие VirtualBox""", "512")
EmptyIniWrite($russian, "start", "01", """Скопируйте файлы из VirtualBox в соответствующих папку в APP директории""", "512")
EmptyIniWrite($russian, "settings", "01", """Настройки""", "512")
EmptyIniWrite($russian, "settings", "02", """Запуск VirtualBox с поддержкой сети""", "512")
EmptyIniWrite($russian, "settings", "03", """Запуск VirtualBox с поддержкой usb""", "512")
EmptyIniWrite($russian, "settings", "04", """Запуск VirtualBox с поддержкой горячих клавиш в трее""", "512")
EmptyIniWrite($russian, "settings", "05", """Язык интерфейса:""", "512")
EmptyIniWrite($russian, "settings", "06", """Папка для сохранения настроек VirtualBox:""", "512")
EmptyIniWrite($russian, "settings", "07", """Папка для сохранения файлов машин:""", "512")
EmptyIniWrite($russian, "settings", "08", """Запускать VirtualBox с VM:""", "512")
EmptyIniWrite($russian, "settings", "09", """Обзор""", "512")
EmptyIniWrite($russian, "settings", "10", """Выберите домашнюю директорию""", "512")
EmptyIniWrite($russian, "settings", "11", """Выберите VM директорию""", "512")
EmptyIniWrite($russian, "hotkey-settings", "01", """Горячие клавиши-настройка""", "512")
EmptyIniWrite($russian, "hotkey-settings", "02", """Тут вы можете изменить значения горячих клавиш. Примечание: вы можете использовать клавиши ALT, CTRL и SHIFT. (По умолчанию = CTRL+""1-6"")""", "512")
EmptyIniWrite($russian, "hotkey-settings", "03", """По умолчанию (CTRL+""1 до 6"")""", "512")
EmptyIniWrite($russian, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "512")
EmptyIniWrite($russian, "about", "01", """О программе...""", "512")
EmptyIniWrite($russian, "download", "01", """VirtualBox Portable""", "512")
EmptyIniWrite($russian, "download", "02", """Здесь вы можете найти установочные файлы VirtualBox, которые можно автоматически загрузить и внести некоторые изменения просто выполните настройки и нажмите ""Применить"".""", "512")
EmptyIniWrite($russian, "download", "03", """Скачать установочные файлы VirtualBox""", "512")
EmptyIniWrite($russian, "download", "04", """или""", "512")
EmptyIniWrite($russian, "download", "05", """Путь к установочному файлу VirtualBox...""", "512")
EmptyIniWrite($russian, "download", "06", """Обзор""", "512")
EmptyIniWrite($russian, "download", "07", """Распаковать файлы для 32-битных систем""", "512")
EmptyIniWrite($russian, "download", "08", """Распаковать файлы для 64-битных систем""", "512")
EmptyIniWrite($russian, "download", "09", """Сжать файлы для уменьшения размера""", "512")
EmptyIniWrite($russian, "download", "10", """Запустить VirtualBox Portable после распаковк""", "512")
EmptyIniWrite($russian, "download", "11", """Статус:""", "512")
EmptyIniWrite($russian, "download", "12", """Применить""", "512")
EmptyIniWrite($russian, "download", "13", """Лицензия VirtualBox""", "512")
EmptyIniWrite($russian, "download", "14", """Выход""", "512")
EmptyIniWrite($russian, "download", "15", """Инфо""", "512")
EmptyIniWrite($russian, "download", "16", """Пожалуйста перезапустите VirtualBox, чтобы адаптировать пути""", "512")
EmptyIniWrite($russian, "status", "01", """Загрузка:""", "512")
EmptyIniWrite($russian, "status", "02", """Загрузка завершена! Файлы хранятся в папке Portable-VirtualBox.VirtualBox - Установка файлов""", "512")
EmptyIniWrite($russian, "status", "03", """VirtualBox - Установка файлов""", "512")
EmptyIniWrite($russian, "status", "04", """Подождите, распаковка файлов.""", "512")
EmptyIniWrite($russian, "status", "05", """Подождите, копирование файлов.""", "512")
EmptyIniWrite($russian, "status", "06", """Подождите, сжатие файлов.""", "512")
EmptyIniWrite($russian, "status", "07", """Подождите, удаление файлов и папок""", "512")
EmptyIniWrite($russian, "status", "08", """Распаковка, копирование файлов завершены""", "512")
EmptyIniWrite($russian, "status", "09", """Подождите, бэкап старых файлов и папок.""", "512")
EmptyIniWrite($russian, "status", "10", """Подождите, загрузка обновлений.""", "512")
EmptyIniWrite($russian, "status", "11", """Подождите, обновление файлов и папок.""", "512")
EmptyIniWrite($russian, "status", "12", """Обновление завершено.""", "512")

EmptyIniWrite($spanish, "tray", "01", """Mostrar VM""", "32")
EmptyIniWrite($spanish, "tray", "02", """Ocultar VM""", "32")
EmptyIniWrite($spanish, "tray", "03", """Mostrar VirtualBox""", "32")
EmptyIniWrite($spanish, "tray", "04", """Ocultar VirtualBox""", "32")
EmptyIniWrite($spanish, "tray", "05", """Ajustes""", "32")
EmptyIniWrite($spanish, "tray", "06", """Salir de VirtualBox""", "32")
EmptyIniWrite($spanish, "tray", "07", """Haga clic con el botón secundario para ver el menú""", "32")
EmptyIniWrite($spanish, "messages", "01", """Error""", "32")
EmptyIniWrite($spanish, "messages", "02", """Ahorrar""", "32")
EmptyIniWrite($spanish, "messages", "03", """Cerrar""", "32")
EmptyIniWrite($spanish, "messages", "04", """Guardado""", "32")
EmptyIniWrite($spanish, "messages", "05", """Por favor, recuerde reiniciar Portable-VirtualBox para que los nuevos ajustes tengan efecto.""", "32")
EmptyIniWrite($spanish, "messages", "06", """Iniciar Portable-VirtualBox""", "32")
EmptyIniWrite($spanish, "messages", "07", """Cerrar VirtualBox""", "32")
EmptyIniWrite($spanish, "start", "01", """Copiar los archivos de VirtualBox en la carpeta correspondiente.""", "32")
EmptyIniWrite($spanish, "settings", "01", """Ajustes""", "32")
EmptyIniWrite($spanish, "settings", "02", """Ejecución de VirtualBox con soporte de red""", "32")
EmptyIniWrite($spanish, "settings", "03", """Ejecución de VirtualBox con soporte USB""", "32")
EmptyIniWrite($spanish, "settings", "04", """Inicie VirtualBox con soporte de teclas de acceso rápido en la bandeja""", "32")
EmptyIniWrite($spanish, "settings", "05", """Idioma de la interfaz:""", "32")
EmptyIniWrite($spanish, "settings", "06", """Carpeta para guardar la configuración de VirtualBox:""", "32")
EmptyIniWrite($spanish, "settings", "07", """Carpeta para guardar archivos de la máquina:""", "32")
EmptyIniWrite($spanish, "settings", "08", """Empezar VirtualBox con VM:""", "32")
EmptyIniWrite($spanish, "settings", "09", """Revisar""", "32")
EmptyIniWrite($spanish, "settings", "10", """Seleccionar directorio de inicio""", "32")
EmptyIniWrite($spanish, "settings", "11", """Seleccionar directorio de VM""", "32")
EmptyIniWrite($spanish, "hotkey-settings", "01", """Ajustes de HotKeys""", "32")
EmptyIniWrite($spanish, "hotkey-settings", "02", """Si no está conforme con los ajustes predeterminados de las HotKeys (accesos directos por teclado), puede especificar aquí sus propias combinaciones de teclas. Nota: Las teclas de control se limitan a Alt, Ctrl y Mayús, la tecla restante puede elegirse libremente (por defecto, Ctrl+""1 a 6"").""", "32")
EmptyIniWrite($spanish, "hotkey-settings", "03", """POR DEFECTO (CTRL+""1 a 6"")""", "32")
EmptyIniWrite($spanish, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "32")
EmptyIniWrite($spanish, "about", "01", """Sobre el programa...""", "32")
EmptyIniWrite($spanish, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($spanish, "download", "02", """Aquí puede descargar automáticamente los archivos de instalación de VirtualBox y hacer algunos ajustes (Si utiliza este script para descargar VirtualBox, sólo hay que realizar los ajustes y hacer clic en ""Aceptar"").""", "32")
EmptyIniWrite($spanish, "download", "03", """Descargar archivos de instalación de VirtualBox""", "32")
EmptyIniWrite($spanish, "download", "04", """o""", "32")
EmptyIniWrite($spanish, "download", "05", """La ruta del archivo de instalación de VirtualBox es...""", "32")
EmptyIniWrite($spanish, "download", "06", """Revisar""", "32")
EmptyIniWrite($spanish, "download", "07", """Desempaquetar archivos para sistemas de 32 bits""", "32")
EmptyIniWrite($spanish, "download", "08", """Desempaquetar archivos para sistemas de 64 bits""", "32")
EmptyIniWrite($spanish, "download", "09", """Comprimir los archivos para reducir el espacio de almacenamiento ocupado""", "32")
EmptyIniWrite($spanish, "download", "10", """Iniciar Portable-VirtualBox después de la extracción""", "32")
EmptyIniWrite($spanish, "download", "11", """Información de estado:""", "32")
EmptyIniWrite($spanish, "download", "12", """Aceptar""", "32")
EmptyIniWrite($spanish, "download", "13", """Licencia de VirtualBox""", "32")
EmptyIniWrite($spanish, "download", "14", """Salida""", "32")
EmptyIniWrite($spanish, "download", "15", """Info""", "32")
EmptyIniWrite($spanish, "download", "16", """Por favor, reinicie VirtualBox, para que todas las rutas se puedan ajustar!""", "32")
EmptyIniWrite($spanish, "status", "01", """Descargando:""", "32")
EmptyIniWrite($spanish, "status", "02", """¡Descarga finalizada! Los archivos se guardaron en la carpeta de Portable-VirtualBox""", "32")
EmptyIniWrite($spanish, "status", "03", """VirtualBox - Archivo de instalación""", "32")
EmptyIniWrite($spanish, "status", "04", """Por favor, espere, extrayendo archivos.""", "32")
EmptyIniWrite($spanish, "status", "05", """Por favor, espere, copiando archivos.""", "32")
EmptyIniWrite($spanish, "status", "06", """Por favor, espere, comprimiendo archivos.""", "32")
EmptyIniWrite($spanish, "status", "07", """Por favor, espere, borrando archivos y carpetas.""", "32")
EmptyIniWrite($spanish, "status", "08", """Ha finalizado la extracción y/o compresión y copia de archivos.""", "32")
EmptyIniWrite($spanish, "status", "09", """Por favor, espere, haciendo copia de seguridad de los archivos y carpetas antiguos.""", "32")
EmptyIniWrite($spanish, "status", "10", """Por favor, espere, descargando actualización.""", "32")
EmptyIniWrite($spanish, "status", "11", """Por favor, espere, actualizando archivos y carpetas.""", "32")
EmptyIniWrite($spanish, "status", "12", """Actualización terminada.""", "32")

EmptyIniWrite($turkish, "tray", "01", """Sanal Makineyi Göster""", "32")
EmptyIniWrite($turkish, "tray", "02", """Sanal Makineyi Gizle""", "32")
EmptyIniWrite($turkish, "tray", "03", """VirtualBox Göster""", "32")
EmptyIniWrite($turkish, "tray", "04", """VirtualBox'u Gizle""", "32")
EmptyIniWrite($turkish, "tray", "05", """Ayarlar""", "32")
EmptyIniWrite($turkish, "tray", "06", """VirtualBox dan Çık""", "32")
EmptyIniWrite($turkish, "tray", "07", """Menüyü görmek için sağ tıklayın""", "32")
EmptyIniWrite($turkish, "messages", "01", """Hata""", "32")
EmptyIniWrite($turkish, "messages", "02", """Kaydet""", "32")
EmptyIniWrite($turkish, "messages", "03", """Çık""", "32")
EmptyIniWrite($turkish, "messages", "04", """Kaydedildi""", "32")
EmptyIniWrite($turkish, "messages", "05", """Değişikliklerin geçerli olabilmesi için VirtualBox yeniden başlatın.""", "32")
EmptyIniWrite($turkish, "messages", "06", """Başlatma Portable-VirtualBox""", "32")
EmptyIniWrite($turkish, "messages", "07", """VirtualBox'ı Kapatma""", "32")
EmptyIniWrite($turkish, "start", "01", """Dosyaları VirtualBox'un ilgili uygulama klasörüne kopyalayın.""", "32")
EmptyIniWrite($turkish, "settings", "01", """Ayarlar""", "32")
EmptyIniWrite($turkish, "settings", "02", """Ağ Desteği ile VirtualBox'ı Çalıştırma""", "32")
EmptyIniWrite($turkish, "settings", "03", """USB desteğiyle VirtualBox'ı çalıştırma""", "32")
EmptyIniWrite($turkish, "settings", "04", """VirtualBox'ı tepsi kısayol tuşu desteğiyle başlatın""", "32")
EmptyIniWrite($turkish, "settings", "05", """Arayüz dili:""", "32")
EmptyIniWrite($turkish, "settings", "06", """VirtualBox ayarlarının kaydedileceği klasör:""", "32")
EmptyIniWrite($turkish, "settings", "07", """Makine dosyalarını kaydetme klasörü:""", "32")
EmptyIniWrite($turkish, "settings", "08", """VirtualBox'ı VM'den çalıştırın:""", "32")
EmptyIniWrite($turkish, "settings", "09", """inceleme""", "32")
EmptyIniWrite($turkish, "settings", "10", """Ana dizini seçin""", "32")
EmptyIniWrite($turkish, "settings", "11", """VM dizinini seçin""", "32")
EmptyIniWrite($turkish, "hotkey-settings", "01", """Kısayol Tuşu Ayarları""", "32")
EmptyIniWrite($turkish, "hotkey-settings", "02", """Hazır ayardan başka Kısayol Tuşları seçmek için, burada kendi komutlarınızı belirtin. Not: Komut tuşları ALT, CTRL ve SHIFT ile sınırlıdır. Son anahtar kendiliğinden tanımlanmıştır. (Varsayılan = CTRL ""1 to 6"")""", "32")
EmptyIniWrite($turkish, "hotkey-settings", "03", """Varsayılan (CTRL+""1 to 6"")""", "32")
EmptyIniWrite($turkish, "hotkey-settings", "04", """Определите клавишу для поля ввода""", "32")
EmptyIniWrite($turkish, "about", "01", """Program hakkında...""", "32")
EmptyIniWrite($turkish, "download", "01", """Portable-VirtualBox""", "32")
EmptyIniWrite($turkish, "download", "02", """Burada VirtualBox'un kurulum dosyalarını otomatik olarak indirebilir ve bazı ayarlamalar yapabilirsiniz. (VirtualBox'u indiren bu scripti kullanırsanız, sadece ayarları yapın ve ""Tamam""ı tıklayın).""", "32")
EmptyIniWrite($turkish, "download", "03", """VirtualBox kurulum dosyalarını indir""", "32")
EmptyIniWrite($turkish, "download", "04", """veya""", "32")
EmptyIniWrite($turkish, "download", "05", """VirtualBox kurulum dosyaları yolu...""", "32")
EmptyIniWrite($turkish, "download", "06", """Gözden geçirmek""", "32")
EmptyIniWrite($turkish, "download", "07", """32-Bit sistemler için dosyaları ayıkla""", "32")
EmptyIniWrite($turkish, "download", "08", """64-Bit sistemler için dosyaları ayıkla""", "32")
EmptyIniWrite($turkish, "download", "09", """Boyutu küçültmek için dosyaları sıkıştır""", "32")
EmptyIniWrite($turkish, "download", "10", """Ayıklama ve/veya sıkıştırma sonrası Portable-VirtualBox'u çalıştır""", "32")
EmptyIniWrite($turkish, "download", "11", """Durum Bilgisi:""", "32")
EmptyIniWrite($turkish, "download", "12", """Tamam""", "32")
EmptyIniWrite($turkish, "download", "13", """Lisansı VirtualBox""", "32")
EmptyIniWrite($turkish, "download", "14", """Çıkış""", "32")
EmptyIniWrite($turkish, "download", "15", """Bilgi""", "32")
EmptyIniWrite($turkish, "download", "16", """Lütfen VirtualBox'u tekrar başlatın, böylece tüm dizinler ayarlanabilir!""", "32")
EmptyIniWrite($turkish, "status", "01", """İndiriliyor:""", "32")
EmptyIniWrite($turkish, "status", "02", """İndirme tamamlandı! Dosyalar Portable-VirtualBox klasöründe saklanır.""", "32")
EmptyIniWrite($turkish, "status", "03", """VirtualBox Kurulum Dosyası""", "32")
EmptyIniWrite($turkish, "status", "04", """VirtualBox - Dosyası yükleme""", "32")
EmptyIniWrite($turkish, "status", "05", """Dosyalar kopyalanıyor, lütfen bekleyin.""", "32")
EmptyIniWrite($turkish, "status", "06", """Dosyalar sıkıştırılıyor, lütfen bekleyin.""", "32")
EmptyIniWrite($turkish, "status", "07", """Dosya ve dizinler siliniyor, lütfen bekleyin.""", "32")
EmptyIniWrite($turkish, "status", "08", """Dosyaların ayıklanması ve/veya sıkıştırılması ve kopyalanması tamamlandı.""", "32")
EmptyIniWrite($turkish, "status", "09", """Dosyaların ayıklanması ve/veya sıkıştırılması ve kopyalanması tamamlandı.""", "32")
EmptyIniWrite($turkish, "status", "10", """Güncelleme indiriliyor, lütfen bekleyin.""", "32")
EmptyIniWrite($turkish, "status", "11", """Dosya ve dizinler güncelleniyor, lütfen bekleyin.""", "32")
EmptyIniWrite($turkish, "status", "12", """Güncelleme tamamlandı.""", "32")

EmptyIniWrite($ukrainian, "tray", "01", """Показати VM""", "512")
EmptyIniWrite($ukrainian, "tray", "02", """Сховати VM""", "512")
EmptyIniWrite($ukrainian, "tray", "03", """Показати VirtualBox""", "512")
EmptyIniWrite($ukrainian, "tray", "04", """Сховати VirtualBox""", "512")
EmptyIniWrite($ukrainian, "tray", "05", """Налаштування""", "512")
EmptyIniWrite($ukrainian, "tray", "06", """Вийти VirtualBox""", "512")
EmptyIniWrite($ukrainian, "tray", "07", """Щоб побачити меню – клацніть правою клавішою миші""", "512")
EmptyIniWrite($ukrainian, "messages", "01", """Помилка""", "512")
EmptyIniWrite($ukrainian, "messages", "02", """Зберегти""", "512")
EmptyIniWrite($ukrainian, "messages", "03", """Закрити""", "512")
EmptyIniWrite($ukrainian, "messages", "04", """Збережено""", "512")
EmptyIniWrite($ukrainian, "messages", "05", """Перезапустіть VirtualBox, щоб змінити налаштування.""", "512")
EmptyIniWrite($ukrainian, "messages", "06", """Запустити Портативний-VirtualBox""", "512")
EmptyIniWrite($ukrainian, "messages", "07", """Вийти з Портативного-VirtualBox""", "512")
EmptyIniWrite($ukrainian, "start", "01", """Скопіюйте файли VirtualBox у відповідну програмну.""", "512")
EmptyIniWrite($ukrainian, "settings", "01", """Налаштування""", "512")
EmptyIniWrite($ukrainian, "settings", "02", """Запуск VirtualBox із підтримкою мережі""", "512")
EmptyIniWrite($ukrainian, "settings", "03", """Запуск VirtualBox із підтримкою usb""", "512")
EmptyIniWrite($ukrainian, "settings", "04", """Запуск VirtualBox із підтримкою гарячих клавіш у треї""", "512")
EmptyIniWrite($ukrainian, "settings", "05", """Мова інтерфейсу:""", "512")
EmptyIniWrite($ukrainian, "settings", "06", """Папка для збереження налаштувань VirtualBox:""", "512")
EmptyIniWrite($ukrainian, "settings", "07", """Папка для збереження файлів машин:""", "512")
EmptyIniWrite($ukrainian, "settings", "08", """Запускати VirtualBox з VM:""", "512")
EmptyIniWrite($ukrainian, "settings", "09", """Огляд""", "512")
EmptyIniWrite($ukrainian, "settings", "10", """Виберіть домашню директорію""", "512")
EmptyIniWrite($ukrainian, "settings", "11", """Виберіть VM директорію""", "512")
EmptyIniWrite($ukrainian, "hotkey-settings", "01", """Гарячі клавіші-налаштування""", "512")
EmptyIniWrite($ukrainian, "hotkey-settings", "02", """Тут можна змінити значення гарячих клавіш. Примітка: Ви можете використовувати клавіші ALT, CTRL та SHIFT. (ЗА УМОВЧЕННЯМ. = CTRL+""1-6"")""", "512")
EmptyIniWrite($ukrainian, "hotkey-settings", "03", """За замовчуванням. (CTRL+""1-6"")""", "512")
EmptyIniWrite($ukrainian, "hotkey-settings", "04", """Визначте клавішу поля введення""", "512")
EmptyIniWrite($ukrainian, "about", "01", """Про програму...""", "512")
EmptyIniWrite($ukrainian, "download", "01", """Портативний-VirtualBo""", "512")
EmptyIniWrite($ukrainian, "download", "02", """Тут ви можете знайти інсталяційні файли VirtualBox, які можна автоматично завантажити та внести деякі зміни просто виконайте налаштування та натисніть ""Гаразд"".""", "512")
EmptyIniWrite($ukrainian, "download", "03", """Завантажити файли інсталяції VirtualBox""", "512")
EmptyIniWrite($ukrainian, "download", "04", """ЧИ""", "512")
EmptyIniWrite($ukrainian, "download", "05", """Шлях до файлу інсталяції VirtualBox...""", "512")
EmptyIniWrite($ukrainian, "download", "06", """Огляд""", "512")
EmptyIniWrite($ukrainian, "download", "07", """Видобути файли для 32-бітної системиm""", "512")
EmptyIniWrite($ukrainian, "download", "08", """Видобути файли для 64-бітної системиm""", "512")
EmptyIniWrite($ukrainian, "download", "09", """Стиснути файли аби зменшити розмір""", "512")
EmptyIniWrite($ukrainian, "download", "10", """Запустити VirtualBox Portable після розпакування""", "512")
EmptyIniWrite($ukrainian, "download", "11", """Статус-інформ.:""", "512")
EmptyIniWrite($ukrainian, "download", "12", """Гаразд""", "512")
EmptyIniWrite($ukrainian, "download", "13", """Ліцензія VirtualBox""", "512")
EmptyIniWrite($ukrainian, "download", "14", """Вихід""", "512")
EmptyIniWrite($ukrainian, "download", "15", """Інформ.""", "512")
EmptyIniWrite($ukrainian, "download", "16", """Будь ласка запустіте VirtualBox знову щоб усі шляхи могли оновитися""", "512")
EmptyIniWrite($ukrainian, "status", "01", """Завантажується:""", "512")
EmptyIniWrite($ukrainian, "status", "02", """Завантаження завершено; файли збережено у теці портативного VirtualBox.""", "512")
EmptyIniWrite($ukrainian, "status", "03", """VirtualBox – Інсталяція файлів""", "512")
EmptyIniWrite($ukrainian, "status", "04", """Будь ласка, видобування файлів.""", "512")
EmptyIniWrite($ukrainian, "status", "05", """Будь ласка, копіювання файлів.""", "512")
EmptyIniWrite($ukrainian, "status", "06", """Будь ласка, стиснення файлів.""", "512")
EmptyIniWrite($ukrainian, "status", "07", """Будь ласка, вилучаються файли та теки.""", "512")
EmptyIniWrite($ukrainian, "status", "08", """Завершено видобування та/або копіювання файлів.""", "512")
EmptyIniWrite($ukrainian, "status", "09", """Будь ласка, робиться резерв. Копія файлів.""", "512")
EmptyIniWrite($ukrainian, "status", "10", """Будь ласка, завантажується оновлення.""", "512")
EmptyIniWrite($ukrainian, "status", "11", """Будь ласка, оновлюються файли та теки.""", "512")
EmptyIniWrite($ukrainian, "status", "12", """Оновлення завершено.""", "512")